// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/email.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SendEmailRequest struct {
	To                   []*Person `protobuf:"bytes,1,rep,name=to,proto3" json:"to,omitempty"`
	From                 *Person   `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Cc                   []*Person `protobuf:"bytes,3,rep,name=cc,proto3" json:"cc,omitempty"`
	Bcc                  []*Person `protobuf:"bytes,4,rep,name=bcc,proto3" json:"bcc,omitempty"`
	Subject              string    `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	TemplateId           string    `protobuf:"bytes,6,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	EmailType            Type      `protobuf:"varint,7,opt,name=email_type,json=emailType,proto3,enum=proto.Type" json:"email_type,omitempty"`
	JsonData             []string  `protobuf:"bytes,8,rep,name=json_data,json=jsonData,proto3" json:"json_data,omitempty"`
	AttachamentContent   []byte    `protobuf:"bytes,9,opt,name=attachament_content,json=attachamentContent,proto3" json:"attachament_content,omitempty"`
	AttachmentName       string    `protobuf:"bytes,11,opt,name=attachment_name,json=attachmentName,proto3" json:"attachment_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SendEmailRequest) Reset()         { *m = SendEmailRequest{} }
func (m *SendEmailRequest) String() string { return proto.CompactTextString(m) }
func (*SendEmailRequest) ProtoMessage()    {}
func (*SendEmailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{0}
}

func (m *SendEmailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailRequest.Unmarshal(m, b)
}
func (m *SendEmailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailRequest.Marshal(b, m, deterministic)
}
func (m *SendEmailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailRequest.Merge(m, src)
}
func (m *SendEmailRequest) XXX_Size() int {
	return xxx_messageInfo_SendEmailRequest.Size(m)
}
func (m *SendEmailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailRequest proto.InternalMessageInfo

func (m *SendEmailRequest) GetTo() []*Person {
	if m != nil {
		return m.To
	}
	return nil
}

func (m *SendEmailRequest) GetFrom() *Person {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *SendEmailRequest) GetCc() []*Person {
	if m != nil {
		return m.Cc
	}
	return nil
}

func (m *SendEmailRequest) GetBcc() []*Person {
	if m != nil {
		return m.Bcc
	}
	return nil
}

func (m *SendEmailRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SendEmailRequest) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *SendEmailRequest) GetEmailType() Type {
	if m != nil {
		return m.EmailType
	}
	return Type_Promotional
}

func (m *SendEmailRequest) GetJsonData() []string {
	if m != nil {
		return m.JsonData
	}
	return nil
}

func (m *SendEmailRequest) GetAttachamentContent() []byte {
	if m != nil {
		return m.AttachamentContent
	}
	return nil
}

func (m *SendEmailRequest) GetAttachmentName() string {
	if m != nil {
		return m.AttachmentName
	}
	return ""
}

type Person struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Person) Reset()         { *m = Person{} }
func (m *Person) String() string { return proto.CompactTextString(m) }
func (*Person) ProtoMessage()    {}
func (*Person) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{1}
}

func (m *Person) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Person.Unmarshal(m, b)
}
func (m *Person) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Person.Marshal(b, m, deterministic)
}
func (m *Person) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Person.Merge(m, src)
}
func (m *Person) XXX_Size() int {
	return xxx_messageInfo_Person.Size(m)
}
func (m *Person) XXX_DiscardUnknown() {
	xxx_messageInfo_Person.DiscardUnknown(m)
}

var xxx_messageInfo_Person proto.InternalMessageInfo

func (m *Person) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Person) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type SendEmailResponse struct {
	Status               bool       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Code                 StatusCode `protobuf:"varint,2,opt,name=code,proto3,enum=proto.StatusCode" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SendEmailResponse) Reset()         { *m = SendEmailResponse{} }
func (m *SendEmailResponse) String() string { return proto.CompactTextString(m) }
func (*SendEmailResponse) ProtoMessage()    {}
func (*SendEmailResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_90f7cc01862a1851, []int{2}
}

func (m *SendEmailResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendEmailResponse.Unmarshal(m, b)
}
func (m *SendEmailResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendEmailResponse.Marshal(b, m, deterministic)
}
func (m *SendEmailResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendEmailResponse.Merge(m, src)
}
func (m *SendEmailResponse) XXX_Size() int {
	return xxx_messageInfo_SendEmailResponse.Size(m)
}
func (m *SendEmailResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendEmailResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendEmailResponse proto.InternalMessageInfo

func (m *SendEmailResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *SendEmailResponse) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_Unknown
}

func (m *SendEmailResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*SendEmailRequest)(nil), "proto.SendEmailRequest")
	proto.RegisterType((*Person)(nil), "proto.Person")
	proto.RegisterType((*SendEmailResponse)(nil), "proto.SendEmailResponse")
}

func init() {
	proto.RegisterFile("proto/email.proto", fileDescriptor_90f7cc01862a1851)
}

var fileDescriptor_90f7cc01862a1851 = []byte{
	// 431 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xe5, 0x7c, 0x35, 0x9e, 0x94, 0x40, 0x06, 0x04, 0xab, 0x22, 0x54, 0x13, 0x09, 0x61,
	0x21, 0x25, 0x91, 0x52, 0xf1, 0x00, 0x50, 0x38, 0x70, 0x41, 0xe0, 0x70, 0xea, 0x25, 0xda, 0xac,
	0x87, 0x34, 0x95, 0x77, 0xd7, 0x64, 0x27, 0x48, 0x7d, 0x6d, 0x9e, 0x00, 0x79, 0x36, 0x16, 0x15,
	0xed, 0xc9, 0x33, 0xf3, 0xfb, 0xeb, 0x3f, 0x1f, 0x5e, 0x98, 0xd4, 0x7b, 0xcf, 0x7e, 0x41, 0x56,
	0xef, 0xaa, 0xb9, 0xc4, 0xd8, 0x97, 0xcf, 0x19, 0x46, 0x62, 0xbc, 0xb5, 0xde, 0x45, 0x34, 0xfd,
	0xd3, 0x81, 0x27, 0x2b, 0x72, 0xe5, 0xe7, 0x46, 0x5e, 0xd0, 0xaf, 0x03, 0x05, 0xc6, 0x57, 0xd0,
	0x61, 0xaf, 0x92, 0xac, 0x9b, 0x8f, 0x96, 0x8f, 0xa2, 0x70, 0xfe, 0x8d, 0xf6, 0xc1, 0xbb, 0xa2,
	0xc3, 0x1e, 0x5f, 0x43, 0xef, 0xe7, 0xde, 0x5b, 0xd5, 0xc9, 0x92, 0xfb, 0x02, 0x41, 0x8d, 0x83,
	0x31, 0xaa, 0xfb, 0xa0, 0x83, 0x31, 0x78, 0x0e, 0xdd, 0x8d, 0x31, 0xaa, 0xf7, 0x10, 0x6f, 0x08,
	0x2a, 0x38, 0x09, 0x87, 0xcd, 0x0d, 0x19, 0x56, 0xfd, 0x2c, 0xc9, 0xd3, 0xa2, 0x4d, 0xf1, 0x1c,
	0x46, 0x4c, 0xb6, 0xae, 0x34, 0xd3, 0x7a, 0x57, 0xaa, 0x81, 0x50, 0x68, 0x4b, 0x5f, 0x4a, 0x7c,
	0x07, 0x20, 0xbb, 0xaf, 0xf9, 0xb6, 0x26, 0x75, 0x92, 0x25, 0xf9, 0x78, 0x39, 0x3a, 0xb6, 0xf8,
	0x71, 0x5b, 0x53, 0x91, 0x0a, 0x6e, 0x42, 0x7c, 0x09, 0xe9, 0x4d, 0xf0, 0x6e, 0x5d, 0x6a, 0xd6,
	0x6a, 0x98, 0x75, 0xf3, 0xb4, 0x18, 0x36, 0x85, 0x4f, 0x9a, 0x35, 0x2e, 0xe0, 0xa9, 0x66, 0xd6,
	0xe6, 0x5a, 0x5b, 0x72, 0xbc, 0x36, 0xde, 0x31, 0x39, 0x56, 0x69, 0x96, 0xe4, 0xa7, 0x05, 0xde,
	0x41, 0x97, 0x91, 0xe0, 0x5b, 0x78, 0x1c, 0xab, 0xa2, 0x77, 0xda, 0x92, 0x1a, 0xc9, 0x78, 0xe3,
	0x7f, 0xe5, 0xaf, 0xda, 0xd2, 0x74, 0x09, 0x83, 0xb8, 0x2c, 0x22, 0xf4, 0x44, 0x97, 0x88, 0x4e,
	0x62, 0x7c, 0x06, 0x7d, 0x99, 0x50, 0xee, 0x9b, 0x16, 0x31, 0x99, 0x56, 0x30, 0xb9, 0xf3, 0x9f,
	0x42, 0xed, 0x5d, 0x20, 0x7c, 0x0e, 0x83, 0xc0, 0x9a, 0x0f, 0x41, 0x0c, 0x86, 0xc5, 0x31, 0xc3,
	0x37, 0xd0, 0x33, 0xbe, 0x24, 0x71, 0x18, 0x2f, 0x27, 0xc7, 0xed, 0x57, 0x02, 0x2f, 0x7d, 0x49,
	0x85, 0xe0, 0xe6, 0xca, 0x96, 0x42, 0xd0, 0x5b, 0x52, 0xdd, 0x78, 0xe5, 0x63, 0xba, 0xfc, 0x0e,
	0xa7, 0xd2, 0x69, 0x45, 0xfb, 0xdf, 0x3b, 0x43, 0xf8, 0x01, 0x20, 0xb4, 0xdd, 0x03, 0xbe, 0x68,
	0x0d, 0xff, 0x7b, 0x38, 0x67, 0xea, 0x3e, 0x88, 0x93, 0xe6, 0xc9, 0xc7, 0xf7, 0x57, 0x17, 0xdb,
	0x1d, 0x5f, 0x1f, 0x36, 0x73, 0xe3, 0xed, 0xe2, 0xca, 0x5b, 0xdd, 0xbe, 0xd2, 0x59, 0x88, 0x5d,
	0x66, 0xa6, 0xda, 0x91, 0xe3, 0xd9, 0xd6, 0x57, 0xda, 0x6d, 0x17, 0x62, 0xb5, 0x19, 0xc8, 0xe7,
	0xe2, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0x5c, 0xac, 0xa5, 0xd7, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EmailServiceClient is the client API for EmailService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailServiceClient interface {
	SendEmails(ctx context.Context, opts ...grpc.CallOption) (EmailService_SendEmailsClient, error)
}

type emailServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailServiceClient(cc grpc.ClientConnInterface) EmailServiceClient {
	return &emailServiceClient{cc}
}

func (c *emailServiceClient) SendEmails(ctx context.Context, opts ...grpc.CallOption) (EmailService_SendEmailsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_EmailService_serviceDesc.Streams[0], "/proto.EmailService/sendEmails", opts...)
	if err != nil {
		return nil, err
	}
	x := &emailServiceSendEmailsClient{stream}
	return x, nil
}

type EmailService_SendEmailsClient interface {
	Send(*SendEmailRequest) error
	CloseAndRecv() (*SendEmailResponse, error)
	grpc.ClientStream
}

type emailServiceSendEmailsClient struct {
	grpc.ClientStream
}

func (x *emailServiceSendEmailsClient) Send(m *SendEmailRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *emailServiceSendEmailsClient) CloseAndRecv() (*SendEmailResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendEmailResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EmailServiceServer is the server API for EmailService service.
type EmailServiceServer interface {
	SendEmails(EmailService_SendEmailsServer) error
}

// UnimplementedEmailServiceServer can be embedded to have forward compatible implementations.
type UnimplementedEmailServiceServer struct {
}

func (*UnimplementedEmailServiceServer) SendEmails(srv EmailService_SendEmailsServer) error {
	return status.Errorf(codes.Unimplemented, "method SendEmails not implemented")
}

func RegisterEmailServiceServer(s *grpc.Server, srv EmailServiceServer) {
	s.RegisterService(&_EmailService_serviceDesc, srv)
}

func _EmailService_SendEmails_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmailServiceServer).SendEmails(&emailServiceSendEmailsServer{stream})
}

type EmailService_SendEmailsServer interface {
	SendAndClose(*SendEmailResponse) error
	Recv() (*SendEmailRequest, error)
	grpc.ServerStream
}

type emailServiceSendEmailsServer struct {
	grpc.ServerStream
}

func (x *emailServiceSendEmailsServer) SendAndClose(m *SendEmailResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *emailServiceSendEmailsServer) Recv() (*SendEmailRequest, error) {
	m := new(SendEmailRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _EmailService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.EmailService",
	HandlerType: (*EmailServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "sendEmails",
			Handler:       _EmailService_SendEmails_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/email.proto",
}
