// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/template.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Template struct {
	Content              string   `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"`
	TemplateName         string   `protobuf:"bytes,2,opt,name=template_name,json=templateName,proto3" json:"template_name,omitempty"`
	TemplateDescription  string   `protobuf:"bytes,3,opt,name=template_description,json=templateDescription,proto3" json:"template_description,omitempty"`
	TemplateType         Type     `protobuf:"varint,4,opt,name=template_type,json=templateType,proto3,enum=proto.Type" json:"template_type,omitempty"`
	TenantId             string   `protobuf:"bytes,5,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UrlPath              string   `protobuf:"bytes,6,opt,name=url_path,json=urlPath,proto3" json:"url_path,omitempty"`
	Variables            string   `protobuf:"bytes,7,opt,name=variables,proto3" json:"variables,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Template) Reset()         { *m = Template{} }
func (m *Template) String() string { return proto.CompactTextString(m) }
func (*Template) ProtoMessage()    {}
func (*Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc851a26de071022, []int{0}
}

func (m *Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Template.Unmarshal(m, b)
}
func (m *Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Template.Marshal(b, m, deterministic)
}
func (m *Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Template.Merge(m, src)
}
func (m *Template) XXX_Size() int {
	return xxx_messageInfo_Template.Size(m)
}
func (m *Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Template proto.InternalMessageInfo

func (m *Template) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Template) GetTemplateName() string {
	if m != nil {
		return m.TemplateName
	}
	return ""
}

func (m *Template) GetTemplateDescription() string {
	if m != nil {
		return m.TemplateDescription
	}
	return ""
}

func (m *Template) GetTemplateType() Type {
	if m != nil {
		return m.TemplateType
	}
	return Type_Promotional
}

func (m *Template) GetTenantId() string {
	if m != nil {
		return m.TenantId
	}
	return ""
}

func (m *Template) GetUrlPath() string {
	if m != nil {
		return m.UrlPath
	}
	return ""
}

func (m *Template) GetVariables() string {
	if m != nil {
		return m.Variables
	}
	return ""
}

type RegisterTemplateResponse struct {
	Status               bool       `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Code                 StatusCode `protobuf:"varint,2,opt,name=code,proto3,enum=proto.StatusCode" json:"code,omitempty"`
	Message              string     `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RegisterTemplateResponse) Reset()         { *m = RegisterTemplateResponse{} }
func (m *RegisterTemplateResponse) String() string { return proto.CompactTextString(m) }
func (*RegisterTemplateResponse) ProtoMessage()    {}
func (*RegisterTemplateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc851a26de071022, []int{1}
}

func (m *RegisterTemplateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisterTemplateResponse.Unmarshal(m, b)
}
func (m *RegisterTemplateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisterTemplateResponse.Marshal(b, m, deterministic)
}
func (m *RegisterTemplateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisterTemplateResponse.Merge(m, src)
}
func (m *RegisterTemplateResponse) XXX_Size() int {
	return xxx_messageInfo_RegisterTemplateResponse.Size(m)
}
func (m *RegisterTemplateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisterTemplateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisterTemplateResponse proto.InternalMessageInfo

func (m *RegisterTemplateResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *RegisterTemplateResponse) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_Unknown
}

func (m *RegisterTemplateResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Template)(nil), "proto.Template")
	proto.RegisterType((*RegisterTemplateResponse)(nil), "proto.RegisterTemplateResponse")
}

func init() {
	proto.RegisterFile("proto/template.proto", fileDescriptor_dc851a26de071022)
}

var fileDescriptor_dc851a26de071022 = []byte{
	// 352 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x4f, 0x6b, 0x2a, 0x31,
	0x14, 0xc5, 0xd1, 0xe7, 0x9f, 0x31, 0xef, 0x3d, 0x9f, 0x2f, 0x95, 0x92, 0xda, 0x42, 0xc5, 0x52,
	0x70, 0xa3, 0xd3, 0x2a, 0xfd, 0x02, 0xad, 0x9b, 0x6e, 0x4a, 0x99, 0xba, 0x28, 0x6e, 0x24, 0xce,
	0x5c, 0xc6, 0xc0, 0x24, 0x19, 0x92, 0x3b, 0x82, 0xfb, 0x7e, 0xf0, 0x62, 0x66, 0x52, 0x8b, 0xd0,
	0x55, 0x38, 0xe7, 0x77, 0x39, 0xf7, 0xe6, 0x90, 0x7e, 0x6e, 0x34, 0xea, 0x10, 0x41, 0xe6, 0x19,
	0x47, 0x98, 0x3a, 0x49, 0x9b, 0xee, 0x19, 0xd0, 0x12, 0xc6, 0x5a, 0x4a, 0xad, 0x4a, 0x34, 0xfa,
	0xa8, 0x93, 0x60, 0x59, 0x4d, 0x53, 0x46, 0xda, 0xb1, 0x56, 0x08, 0x0a, 0x59, 0x6d, 0x58, 0x1b,
	0x77, 0x22, 0x2f, 0xe9, 0x0d, 0xf9, 0xeb, 0x33, 0xd7, 0x8a, 0x4b, 0x60, 0x75, 0xc7, 0xff, 0x78,
	0xf3, 0x85, 0x4b, 0xa0, 0xf7, 0xa4, 0xff, 0x35, 0x94, 0x80, 0x8d, 0x8d, 0xc8, 0x51, 0x68, 0xc5,
	0x7e, 0xb9, 0xd9, 0x33, 0xcf, 0x16, 0x47, 0x44, 0xef, 0xbe, 0xe5, 0xe2, 0x3e, 0x07, 0xd6, 0x18,
	0xd6, 0xc6, 0xdd, 0xd9, 0xef, 0xf2, 0xba, 0xe9, 0x72, 0x9f, 0xc3, 0x71, 0xc9, 0x41, 0xd1, 0x4b,
	0xd2, 0x41, 0x50, 0x5c, 0xe1, 0x5a, 0x24, 0xac, 0xe9, 0x92, 0x83, 0xd2, 0x78, 0x4e, 0xe8, 0x05,
	0x09, 0x0a, 0x93, 0xad, 0x73, 0x8e, 0x5b, 0xd6, 0x2a, 0x7f, 0x50, 0x98, 0xec, 0x95, 0xe3, 0x96,
	0x5e, 0x91, 0xce, 0x8e, 0x1b, 0xc1, 0x37, 0x19, 0x58, 0xd6, 0x76, 0xec, 0x68, 0x8c, 0x2c, 0x61,
	0x11, 0xa4, 0xc2, 0x22, 0x18, 0xdf, 0x46, 0x04, 0x36, 0xd7, 0xca, 0x02, 0x3d, 0x27, 0x2d, 0x8b,
	0x1c, 0x0b, 0xeb, 0x4a, 0x09, 0xa2, 0x4a, 0xd1, 0x5b, 0xd2, 0x88, 0x75, 0x52, 0x56, 0xd1, 0x9d,
	0xfd, 0xaf, 0x4e, 0x7e, 0x73, 0xf0, 0x49, 0x27, 0x10, 0x39, 0x7c, 0x28, 0x55, 0x82, 0xb5, 0x3c,
	0x85, 0xaa, 0x08, 0x2f, 0x67, 0xef, 0xa4, 0x77, 0xba, 0x94, 0x2e, 0x48, 0xcf, 0x9c, 0x7a, 0xff,
	0x7c, 0x1b, 0x95, 0x31, 0xb8, 0xae, 0x8c, 0x9f, 0x4e, 0x7e, 0x7c, 0x58, 0xcd, 0x53, 0x81, 0xdb,
	0x62, 0x33, 0x8d, 0xb5, 0x0c, 0x57, 0x5a, 0x72, 0xd4, 0x21, 0x48, 0x2e, 0xb2, 0x89, 0x05, 0xb3,
	0x13, 0x31, 0x4c, 0xe2, 0x4c, 0x80, 0xc2, 0x49, 0xaa, 0x33, 0xae, 0xd2, 0xd0, 0xe5, 0x6d, 0x5a,
	0xee, 0x99, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0x52, 0x1e, 0xe5, 0x34, 0x46, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RegisterTemplateClient is the client API for RegisterTemplate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RegisterTemplateClient interface {
	RegisterTemplate(ctx context.Context, in *Template, opts ...grpc.CallOption) (*RegisterTemplateResponse, error)
}

type registerTemplateClient struct {
	cc grpc.ClientConnInterface
}

func NewRegisterTemplateClient(cc grpc.ClientConnInterface) RegisterTemplateClient {
	return &registerTemplateClient{cc}
}

func (c *registerTemplateClient) RegisterTemplate(ctx context.Context, in *Template, opts ...grpc.CallOption) (*RegisterTemplateResponse, error) {
	out := new(RegisterTemplateResponse)
	err := c.cc.Invoke(ctx, "/proto.RegisterTemplate/registerTemplate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RegisterTemplateServer is the server API for RegisterTemplate service.
type RegisterTemplateServer interface {
	RegisterTemplate(context.Context, *Template) (*RegisterTemplateResponse, error)
}

// UnimplementedRegisterTemplateServer can be embedded to have forward compatible implementations.
type UnimplementedRegisterTemplateServer struct {
}

func (*UnimplementedRegisterTemplateServer) RegisterTemplate(ctx context.Context, req *Template) (*RegisterTemplateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterTemplate not implemented")
}

func RegisterRegisterTemplateServer(s *grpc.Server, srv RegisterTemplateServer) {
	s.RegisterService(&_RegisterTemplate_serviceDesc, srv)
}

func _RegisterTemplate_RegisterTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Template)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RegisterTemplateServer).RegisterTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RegisterTemplate/RegisterTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RegisterTemplateServer).RegisterTemplate(ctx, req.(*Template))
	}
	return interceptor(ctx, in, info, handler)
}

var _RegisterTemplate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RegisterTemplate",
	HandlerType: (*RegisterTemplateServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "registerTemplate",
			Handler:    _RegisterTemplate_RegisterTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/template.proto",
}
